### PR TITLE
Bibtex on mac os x

### PR DESCRIPTION
**Pull request by pletzer**
Hi @largek and @mkienzle,

I fixed ./doBuild.sh documentation on Mac OS X (issue 239). This involved:

1. Allowing for operating_system to be "darwin" (previously only allowed for "linux" and "windows".

2. The logic keys off from == "windows" and != "windows" as opposed to != "linux" or == "linux". Mac OS X behaves just like "linux" so "windows" is the exception.

3. I got message errors such as "CASAL2.aux file not found". These were fixed by running latex *before* running bibtex (as well as running after bibtex)

4. The build system added directories such as /usr/bin at the beginning of PATH. I think it should add them at the back because we want to allow users to build with non-system installed compilers. In the previous setup the build was picking up the clang compiler which is not supported.

Please test that the code still builds the documentation on Windows and Linux. There appears to be a way to test an inactive pull-request before accepting the pull request.

### CODE REVIEW

**Comment by Zaita** [comment]
# I would put Globals.path_ after self.original_path_ since we 
      # want the user to be able to build with different versions of
      # compilers... (Alex Pletzer)

This is done to prevent conflicts with systems like R.

**Comment by mkienzle** [comment]
Hi Scott

1. where does R come into play when building CASAL2?
2. can we test that Alex's changes are creating the problem you are
suggesting? Do we have a unit test?
3. We have platforms where we do not want to build CASAL2 with the system
compiler: how do you suggest to go about this?

cheers,
marco

**Comment by Zaita** [comment]
1. The R Tools software comes with GCC, SH etc. These conflict with other installed unixutilities or compilers. Casal2 Build system removes these from the path to ensure it doesn't fail with a weird error because the R Tools version of something was called instead.
2. No. There is no unit test for R Tools compatibility. The change he has suggest doesn't provide value for swapping compilers. I have 3+ compilers on my system and can build Casal2 without issue. Casal2 will also pick the first compiler in the path because this is the one the Operating System returns from the "which" command. 
3. Set the console/environmental path to the compiler path you want to use before calling Casal2 build system.

**Comment by pletzer** [comment]
Hi all, 

Thanks. The build currently fails on Mac OS X because the system g++ is clang 10.0.0 and this is the g++ version detected because system path precedes user defined environment (clang is also called g++). The problem will arise on any platform where the system g++ is not deemed good enough. 

So the problems are:

1. g++ is required even for building the documentation and some the build system will bark if g++ does not satisfy some criteria

2. there is another package, R, which interferes with CASAL2's build system. 

Ideally we want the build system to allow the user to specify the c++ and fortran compilers, giving a full path (?)

Suggestions?

**Comment by pletzer** [comment]
Hi @Zaita,

I'm guessing the reason you can build casal2 with 3 different compilers is that your system compiler passes the test. 

This is what I'm getting 

niwa-1019500:BuildSystem pletzera$ ./doBuild.sh clean 
--> Starting SystemInfo object
-- Configuring for Operating System: darwin
-- Searching path for g++
-- g++ found @ /Users/pletzera/lfric-8-Jun-2018/usr/bin/
-- Searching path for gfortran
-- gfortran found @ /Users/pletzera/lfric-8-Jun-2018/usr/bin/
-- Searching path for bibtex
-- bibtex found @ /Library/TeX/texbin/
-- Searching path for git
-- git found @ /usr/bin/
-- Searching path for unzip
-- unzip found @ /usr/bin/
-- Searching path for cmake
-- cmake found @ /usr/local/bin/
-- Overriding the system path with new values
-- New Path: /usr/local/bin/:/usr/bin/:/usr/bin/:/Library/TeX/texbin/:/Users/pletzera/lfric-8-Jun-2018/usr/bin/:/Users/pletzera/lfric-8-Jun-2018/usr/bin/:/Users/pletzera/CASAL2/BuildSystem/bin/darwin/release_betadiff:/Users/pletzera/lfric-8-Jun-2018/usr/bin:/Users/pletzera/lfric-8-Jun-2018/usr/bin:/usr/local/Cellar/gpg-agent/2.0.31/bin/:/Users/pletzera/fcm-2017.10.0/bin/:/Users/pletzera/bin:/Users/pletzera/miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin
--> Full Version: 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
--> Compiler Version: 10.0.0




###### ERROR ######
Error Description:
G++ version 10.0.0 is not supported due to its age
###### ERROR ######

**Comment by Zaita** [comment]
@pletzer The concept of a "system compiler" is unique to OSX. OSX is kinda weird in that you need to install the official developer tools in order to install brew, in order to install another compiler.

The Casal2 build system has not been designed to run on OSX. So it's not aware of the OSX particularities. It is also not configured to build with CLANG. Only GCC/G++ with GFortran.

If you want to run the Casal2 build system on OSX, then you need to modify your path variable in the shell window you're using so that the GCC compiler you wish to use is the first compiler in the path. This is fairly common practice and how it'd be managed on Windows and Linux. The Casal2 build system is fairly primitive in that it basically asks the Operating System which compiler it should use (by way of the which command). So by changing your path to the compiler you want to use it'll work fine.

Have a look at: https://stackoverflow.com/questions/28970935/osx-replace-gcc-version-4-2-1-with-4-9-installed-via-homebrew

**Comment by mkienzle** [comment]
from Scott on Skype forum:

"I think the easiest fix is to remove the compiler check for documentation builds
Then it won't matter for Alex
That's much better than trying to play with different aspects of the build wrapper which have been written/tested for Windows/Linux and different user configs"

Is this a suitable solution. Ultimately, we want CASAL2 to compile on Mac OSX to allow users/contributors working with this OS. In essence, Alex is proposing steps to do that, starting with the documentation.

**Comment by pletzer** [comment]
Thanks all.

It might be even a little easier than that. I'm realising now that the correct compiler is invoked when building boost, so the following is correct

./build.py:    Globals.compiler_path_ = system_info.find_exe_path('g++') # correct

However, later, in System.py

  def find_gcc_version(self):
    p = subprocess.Popen(["g++", "-v"], stdout=subprocess.PIPE, stderr=subprocess.PIPE) # WRONG
    out, err = p.communicate()
    lines = out.split('\n')
    err_lines = re.split('version', err)
    target_line = err_lines[len(err_lines) - 1].lstrip().rstrip()
    print '--> Full Version: ' + target_line
    pieces = target_line.split(' ')
    if len(pieces) < 2:
      return Globals.PrintError('STD out did not return correct GCC Version format ' + str(len(pieces)) + ': ' + target_line)

    Globals.compiler_version_ = pieces[0].lstrip().rstrip()
    print '--> Compiler Version: ' + Globals.compiler_version_
    
    return True

The wrong version is returned. PR 246 fixes this issue

**Comment by Zaita** [comment]
Any objections to closing this pull request without accepting then?

**Pull request closed without merging**
