### PR TITLE
Merge pull request #1 from NIWAFisheriesModelling/master

### PR DESCRIPTION
**Pull request by Craig44**
UPD: Fork to match master repo

### CODE REVIEW

**Comment by mkienzle** [comment]
Hi Craig,

how are things?

What are you trying to achieve with this pull request exactely?

cheers,
marco

**Comment by Craig44** [comment]
I need this to so that my fork is upto date with the master otherwise my
forked repo thinks that I am ahead of the master. I like for my forked repo
to be upto date with the master.

**Comment by SamikDatta** [comment]
For future reference (I think this may be a constant niggle that we all have to deal with), this page explains quite nicely when you need to do a pull request:

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

**Comment by Zaita** [comment]
I would use this method instead:
https://help.github.com/articles/syncing-a-fork/

**Comment by SamikDatta** [comment]
And finally, for those using the TortoiseGit GUI:

https://www.arundhaj.com/blog/merging-upstream-repository-into-fork-tortoise-git.html

**Comment by mkienzle** [comment]
[ disclaimer: I might be wrong ]

@Craig44 @SamikDatta - it's good practice to talk about how to maintain the CASAL2 repo on GitHub.

@Craig44 : if you want to keep your fork up to date with the project, you need to synchronize your fork with the original repository. It's good practice to do this often to avoid merge conflicts. See how to do this using the link below:

https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

Your fork (a part when you clone the original repository) will always be on a different commit (if for nothing else because the commit message of your pull request from the original repository to your fork will be different). Because in Git, the commit message is part of the commit (see https://help.github.com/articles/changing-a-commit-message/)

IMO the CASAL2 maintainers should not accept in the future your most recent pull request because it did not modify any code.

**Comment by Craig44** [comment]
I agree with all that, was feeling out this fork scenario. This should be
added to the Contributors guide.

**Pull request merged**
